dependencies:
  config:
    - field.storage.node.field_content
    - node.type.article
    - paragraphs.paragraphs_type.hero_media
  module:
    - entity_reference_revisions
settings:
  handler: 'default:paragraph'
  handler_settings:
    negate: 1
    target_bundles:
      hero_media: hero_media
    target_bundles_drag_drop:
      hero_media:
        enabled: true
        weight: -26
field_type: entity_reference_revisions
